version: "3.8"

services:
  lint:
    build:
      context: ./
      dockerfile: Dockerfile.tool
    env_file:
      - env.dev
    volumes:
      - './:/app/py/projects/botchan'
    command: poetry run pylint botchan tests

  fmt:
    build:
      context: ./
      dockerfile: Dockerfile.tool
    env_file:
      - env.dev
    volumes:
      - './:/app/py/projects/botchan'
    command:
        - /bin/sh
        - -c
        - |
          echo "Apply isort"
          poetry run isort --profile black botchan tests
          echo "Aplly black"
          poetry run black botchan tests
          echo "change owner to $CURRENT_UID"
          chown -R $CURRENT_UID botchan tests

  ## For shell access and involve tooling, code are mounted
  shell:
    build:
      context: ./
      dockerfile: Dockerfile.tool
    env_file:
      - env.dev
    volumes:
      - './:/app/py/projects/botchan'
    command: /bin/bash -c "while true; do sleep 3600; done"