version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - env.prod
    command: poetry run cli start
    ports:
      - 3000:3000

  app-dev:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - env.dev
    command: poetry run cli start
    ports:
      - 3000:3000

  ## For quick testing, code are mounted
  test:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - env.dev
    volumes:
      - './:/app/py/projects/botchan'
    command: 
        - /bin/sh
        - -c
        - |
          poetry run cli test

  ## For shell access and involve tooling, code are mounted
  shell:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - env.dev
    volumes:
      - './:/app/py/projects/botchan'
    command: /bin/bash -c "while true; do sleep 3600; done"