services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    command: poetry run cli start  --log-level info
    ports:
      - 3000:3000

  app-debug:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.
    command: poetry run cli start  --log-level debug
    ports:
      - 3000:3000



  ## For quick testing, code are mounted
  backdoor:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - './botchan:/app/home/botchan'
      - './tests:/app/home/tests'
    command: 
        - /bin/sh
        - -c
        - |
          poetry run cli backdoor

  ## For run unit test
  test:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.ci  
    command: poetry run pytest --verbose

  ## For shell access and involve tooling, code are mounted
  shell:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - './botchan:/app/home/botchan'
      - './tests:/app/home/tests'
    command: /bin/bash -c "while true; do sleep 3600; done"

