version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - env.prod
    command: poetry run cli start
    ports:
      - 3000:3000

  app-dev:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - env.dev
    command: poetry run cli start
    ports:
      - 3000:3000