[tool.poetry]
name = "botchan"
version = "0.1.0"
description = ""
authors = ["ZF"]

[tool.poetry.dependencies]
python = "^3.9"
structlog = "^23.1.0"
slack-bolt = "^1.18.0"
click = "^8.1.3"
langchain = "^0.0.288"
pydantic = "^1.10.7"
toolz = "^0.12.0"
openai = "^0.27.4"
google-search-results = "^2.4.2"
wikipedia = "^1.4.0"
arxiv = "^1.4.8"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pylint = "^2.17.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.poetry.scripts]
cli = "botchan.cli:main"
