[tool.poetry]
name = "botchan"
version = "0.1.0"
description = ""
authors = ["ZF"]

[tool.poetry.dependencies]
python = "^3.9"
structlog = "^23.1.0"
slack-bolt = "^1.18.0"
click = "^8.1.3"
langchain = "^0.0.150"
pydantic = "^1.10.7"
toolz = "^0.12.0"
openai = "^0.27.4"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
cli = "botchan.cli:main"
