name: intergation

on: [push]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run all tests
      run: docker-compose -f "docker-compose-ci.yml" up --build

